In [140]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
digits=load_digits()

In [141]:
from sklearn.model_selection import train_test_split
x=digits.data
y=digits.target
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [142]:
len(x_train)

1257

In [143]:
len(x_test)

540

In [144]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_train,y_train)


c:\users\honey\appdata\local\programs\python\python39\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [145]:
lr.score(x_test,y_test)

0.9537037037037037

In [146]:
svm=SVC()
svm.fit(x_train,y_train)
svm.score(x_test,y_test)

0.9925925925925926

In [147]:
rf=RandomForestClassifier(n_estimators=40)
rf.fit(x_train,y_train)
rf.score(x_test,y_test)

0.9611111111111111

In [148]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)
# n_splits is no.of flods for model
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [149]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [150]:
def get_score(model,x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)

In [151]:
get_score(SVC(),x_train,x_test,y_train,y_test)


0.9925925925925926

In [152]:
get_score(LogisticRegression(),x_train,x_test,y_train,y_test)

c:\users\honey\appdata\local\programs\python\python39\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9537037037037037

In [153]:
get_score(RandomForestClassifier(n_estimators=40),x_train,x_test,y_train,y_test)

0.9722222222222222

In [154]:
from sklearn.model_selection import StratifiedKFold
folds=StratifiedKFold(n_splits=3)
#KFold and StratifiedKFold methods are same but stratifiedKFold method use uniformly for Kfolds


In [155]:
scores_lr=[]
scores_svm=[]
scores_RFC=[]

for train_index,test_index in kf.split(digits.data):
    x_train,x_test,y_train,y_test=digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]
    print(get_score(LogisticRegression(),x_train,x_test,y_train,y_test))
    print(get_score(SVC(),x_train,x_test,y_train,y_test))
    print(get_score(RandomForestClassifier(),x_train,x_test,y_train,y_test))

c:\users\honey\appdata\local\programs\python\python39\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9232053422370617
0.9666110183639399
0.9465776293823038


c:\users\honey\appdata\local\programs\python\python39\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9415692821368948
0.9816360601001669
0.9616026711185309


c:\users\honey\appdata\local\programs\python\python39\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9148580968280468
0.9549248747913188
0.9248747913188647


In [156]:
scores_lr=[]
scores_svm=[]
scores_RFC=[]

for train_index,test_index in kf.split(digits.data):
    x_train,x_test,y_train,y_test=digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]
    scores_lr.append(get_score(LogisticRegression(),x_train,x_test,y_train,y_test))
    scores_svm.append(get_score(SVC(),x_train,x_test,y_train,y_test))
    scores_RFC.append(get_score(RandomForestClassifier(n_estimators=40),x_train,x_test,y_train,y_test))

c:\users\honey\appdata\local\programs\python\python39\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\users\honey\appdata\local\programs\python\python39\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stab

In [157]:
scores_lr

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [158]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [159]:
scores_RFC

[0.9365609348914858, 0.9565943238731218, 0.9265442404006677]

In [160]:
from sklearn.model_selection import cross_val_score


In [161]:
cross_val_score(LogisticRegression(), digits.data, digits.target)

c:\users\honey\appdata\local\programs\python\python39\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\users\honey\appdata\local\programs\python\python39\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stab

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [162]:
cross_val_score(SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [163]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data,digits.target)

array([0.91666667, 0.89722222, 0.9637883 , 0.96100279, 0.93036212])

In [164]:
cross_val_score(RandomForestClassifier(n_estimators=5),digits.data,digits.target)

array([0.86944444, 0.81944444, 0.88300836, 0.88022284, 0.86629526])

In [165]:
cross_val_score(RandomForestClassifier(n_estimators=15),digits.data,digits.target)

array([0.92777778, 0.88333333, 0.93314763, 0.94707521, 0.8913649 ])

In [166]:
cross_val_score(RandomForestClassifier(n_estimators=60),digits.data,digits.target)

array([0.93055556, 0.91944444, 0.95264624, 0.9637883 , 0.92479109])